### ISSUE TITLE
switchloopfile.py - Telnet error

### ISSUE THREAD

**Issue by martinhoeegh** [davidbombal/pythonvideos#1]
I'm getting an error when I try to run your script and can not figure out what's going wrong

`$ python pythonR1script5.py`

**Enter your remote account:** david
**Password:** cisco 
**Configuring Router** 192.168.1.101

```
Traceback (most recent call last):
  File "pythonR1script5.py", line 13, in <module>
    tn = telnetlib.Telnet(HOST)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**The code:**
```
import getpass
import sys
import telnetlib

user = raw_input("Enter your remote account: ")
password = getpass.getpass()

f = open ('myrouters')

for line in f:
    print "Configuring Router " + (line)
    HOST = line
    tn = telnetlib.Telnet(HOST)

    tn.read_until("Username: ")
    tn.write(user + "\n")
    if password:
        tn.read_until("Password: ")
        tn.write(password + "\n")

    tn.write("conf t\n")

    for n in range (0,2):
        tn.write("interface loopback " + str(n) + "\n")
        tn.write("ip address 1.1." + str(n) + ".2 255.255.255.0\n")

    tn.write("end\n")
    tn.write("exit\n")

    print tn.read_all()

```

**Comment by dazzy099** [comment]
Hi David,

I am getting the similar problem and error when running the for loop script using myswitch file any suggestion ?

**Comment by dazzy099** [comment]
@davidbombal I am getting the similar problem and error when running the for loop script using myswitch file any suggestion ?

Traceback (most recent call last):
  File "diffip.py", line 13, in <module>
    tn = telnetlib.Telnet(HOST)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by sudharshans-s** [comment]
Port timeout is happening, can you normally telnet to the switches.

**Comment by Luck019** [comment]
Try using 
HOST = line.strip()

It is working for me

**Comment by Mandeep4code** [comment]
Hello,

I am new to Python coding and was following David's video on this script.
Even I am getting the same error.

Tried changing the HOST = line.strip() but in vain.

Below is my code:

import getpass
import sys
import telnetlib
import socket

fd = open("C:\\Users\\user\\Desktop\\PYTHON\\HOME\\IP_List.txt")


for line in fd:
    user = "mandeep"
    password = "cisco"
    print "Configuring Routers: " + (line)
	HOST = line
    tn = telnetlib.Telnet(HOST)	
	
    tn.read_until("Username: ")
    tn.write(user + "\n")
    if password:
        tn.read_until("Password: ")
        tn.write(password + "\n")
		
    tn.write("term len 0\n")
    tn.write("sh ip int brief \n")
    tn.write("exit\n")

    print tn.read_all()
	#print (output)
#with open("Health.csv", "wb") as f:
#f.write(output)

**Comment by DilrajSK** [comment]
@Mandeep4code Check if it working with a single Host first.

**Comment by inggreg** [comment]
Hello, Guys
Try using this form:

It is working for me.


       import getpass
       import telnetlib
       import sys

       user = raw_input("Enter your Telnet Username ")
       password = getpass.getpass()

       f = open('myrouters')
       all_ips = [x.rstrip() for x in f] 
       for line in all_ips:

		print ("Configuring Switch " + (line))
		HOST = line
		tn = telnetlib.Telnet(HOST)
		tn.read_until("Username: ")
		tn.write(user.encode('ascii') + "\n")

		if password:
			tn.read_until("Password: ")
			tn.write(password.encode('ascii') + "\n")

		tn.write("config t\n")

		for n in range (0,2):
			tn.write("interface loopback " + str(n) + "\n")
                    tn.write("ip address 1.1." + str(n) + ".2 255.255.255.0\n")

		tn.write("end\n")
		tn.write("wr\n")
		tn.write("exit\n")
		print(tn.read_all().decode('ascii'))

**Comment by raajitengg** [comment]
I tried everything posted here still same error as martinhoeegh and dazzy099. I tried to manually telnet and it works. Even if I use the same code and with single ip address on the code without using the file open it works fine. 
Can someone please help me

**Comment by SejoRikel** [comment]
try HOST=line.strip() it worked for me

**Comment by str8outtajerzy** [comment]
Has anyone ever figured this out? I am having the same problem.

**Comment by arezazadeh** [comment]
i had the same issue, 

HOST = line.strip() works

**Comment by arezazadeh** [comment]
> Has anyone ever figured this out? I am having the same problem.

HOST = line.strip() works

**Comment by arezazadeh** [comment]
does anyone know why we have to use .strip() to get it working?

**Comment by sagarCCIE** [comment]
To some one who landed to this page like how I did for the code that I was facing the issue.
In short :
HOST = line.strip() works

Here is the right script that works:
#!/usr/bin/env python

import getpass
import sys
import telnetlib

user = raw_input("Enter your username: ")
password = getpass.getpass()

f = open ('myswitches')

for line in f:
    print "Configuring Switch " + (line)
    HOST = line.strip()
    tn = telnetlib.Telnet(HOST)

    tn.read_until("Username: ")
    tn.write(user + "\n")
    if password:
        tn.read_until("Password: ")
        tn.write(password + "\n")

    tn.write("conf t\n")

    for n in range (2,26):
        tn.write("vlan " + str(n) + "\n")
        tn.write("name Python_VLAN_" + str(n) + "\n")

    tn.write("end\n")
    tn.write("exit\n")

    print tn.read_all()


In case of further queries please write to me at networkjourneydotcom@gmail.com
Youtube channel for Network automations - https://www.youtube.com/playlist?list=PLtFe0r3PejgnDmMTbFupLxlXTMkFtZGwh

**Comment by xxCRONOxx** [comment]
Tried line.strip () and received the same error, copied the exact code from sagar and tested and same error 

Traceback (most recent call last):
  File "./teststuff", line 15, in <module>
    tn = telnetlib.Telnet(HOST)
  File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -3] Temporary failure in name resolution
root@UbuntuDockerGuest-1:~#

**Comment by arezazadeh** [comment]
Have you tried with a single host first?

**Comment by mirosein** [comment]
> Try using
> HOST = line.strip()
> 
> It is working for me

yes, thank you
it works \m/
