### ISSUE TITLE
Netmiko/Paramiko SSH issue

### ISSUE THREAD

**Issue by Lakshmimidde** [davidbombal/pythonvideos#9]
Hi, when we are trying to config_set with list as below,

config_commands = ['int loop 0', 'ip address 1.1.1.1 255.255.255.0']
output = net_connect.send_config_set(config_commands)
print (output)

We get the following error.

root@Ubuntu-2:~# python3 netmiko1.py
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet0/0     unassigned      YES unset  up                    up
Vlan1                  192.168.47.144  YES manual up                    up
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 534, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netmiko1.py", line 18, in <module>
    output = net_connect.send_config_set(config_commands)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 50, in config_mode
    config_command=config_command, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1514, in config_mode
    if not self.check_config_mode():
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco/cisco_ios.py", line 32, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/cisco_base_connection.py", line 38, in check_config_mode
    check_string=check_string, pattern=pattern
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1501, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 609, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 543, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.
root@Ubuntu-2:~#

**Comment by Lakshmimidde** [comment]
Hi David, the issue has ben identified at switch level, we forgot to issue a privileage command in switch, hence switch rejected the remote users to configure the device. Thank you.
